### ISSUE TITLE
accessing the TreeViewExItem

### ISSUE THREAD

**Issue by nikhilpakki** [tainicom/TreeViewEx#4]
how do I access the TreeViewExItem from TreeViewEx
I was under the assumption that I can access them by:
foreach(TreeViewExItem item in myTreeViewEx.Items)
{
}

**Comment by nkast** [comment]
Items are your items.
TreeViewExItem  is an object used by the control to keep some state of the item internally.
Think of It this way, if your items are the Model then TreeViewExItem is the ViewModel.
